USE [master]
GO

EXEC master..sp_addsrvrolemember @loginame = N'u15207715', @rolename = N'dbcreator'
GO

/****** Object:  Database [ProjectDB ]    Script Date: 2018/04/27 5:09:43 PM ******/
CREATE DATABASE [ProjectDB ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLEXPRESS\MSSQL\DATA\ProjectDB .mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjectDB _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLEXPRESS\MSSQL\DATA\ProjectDB _log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjectDB ] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectDB ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectDB ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectDB ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectDB ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectDB ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectDB ] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectDB ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectDB ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectDB ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectDB ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectDB ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectDB ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectDB ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectDB ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectDB ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectDB ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectDB ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectDB ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectDB ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectDB ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectDB ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectDB ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectDB ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectDB ] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjectDB ] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectDB ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectDB ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectDB ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectDB ] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjectDB ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectDB ] SET  READ_WRITE 
GO


